acemod/ACE-Anvil

docs/src/content/docs/components/medical.mdx
- Title.
- Title of this PR uses our standard template `Component - Add|Fix|Improve|Change|Make|Remove {changes}`.
=> Medical - Fix minor typo in documentation

addons/carrying/Scripts/Game/ACE_Carrying/Entities/ACE_Carrying_Helper.c
- Fix the issue that released players stay prone for other players (see https://discord.com/channels/976165959041679380/1224508065596964985)
- Change `private` constants to `protected` for consistency
=> Carrying - Delay deletion of helper compartment

addons/carrying/Language/ACE_Carrying_localization.cs_cz.conf, addons/carrying/Language/ACE_Carrying_localization.st, addons/chopping/Language/ACE_Chopping_localization.cs_cz.conf, addons/chopping/Language/ACE_Chopping_localization.st, addons/core/Language/ACE_localization.cs_cz.conf, addons/core/Language/ACE_localization.st, addons/finger/Language/ACE_Finger_localization.cs_cz.conf, addons/finger/Language/ACE_Finger_localization.st, addons/medical/Language/ACE_Medical_localization.cs_cz.conf, addons/medical/Language/ACE_Medical_localization.st
- Added Czech localization for carrying, chopping, core, finger and medical
=> Add Czech localization

docs/src/content/docs/components/medical.mdx
=> Docs - Add hint that bool has to be provided as int

addons/carrying/Prefabs/Helpers/ACE_Carrying_HelperCompartment.et, addons/carrying/Prefabs/Helpers/ACE_Carrying_HelperCompartment.et.meta, addons/carrying/Scripts/Game/ACE_Carrying/Entities/ACE_Carrying_HelperCompartment.c, addons/carrying/Scripts/Game/ACE_Carrying/GameMode/SCR_BaseGameMode.c, addons/carrying/Scripts/Game/ACE_Carrying/Tools/ACE_CarryingTools.c, addons/carrying/Scripts/Game/ACE_Carrying/Tools/ACE_Carrying_Tools.c, addons/carrying/Scripts/Game/ACE_Carrying/UI/HUD/AvailableActions/SCR_AvailableActionsConditionData.c, addons/carrying/Scripts/Game/ACE_Carrying/UserActions/ACE_Carrying_CarryUserAction.c, addons/carrying/Scripts/Game/ACE_Carrying/UserActions/SCR_GetInUserAction.c
- Rename helper to helper compartment
- Move static helper methods to separate `ACE_Carrying_Tools` class to decouple them from the helper implementation
- Broadcast attaching/detaching of helper (see https://discord.com/channels/105462288051380224/976155351999201390/1196768025144213516)
- Disable `SCR_UniversalInventoryStorageComponent` on helper compartment
=> Carrying - Clean up helper compartment

addons/core/Prefabs/Items/Core/ACE_Banana.et, addons/core/Prefabs/Weapons/Grenades/ACE_FragBanana.et
=> Core - Increase weight and volume of bananas

addons/carrying/Scripts/Game/ACE_Carrying/Entities/ACE_Carrying_HelperCompartment.c
=> Carrying - Revert to not broadcast attaching/detaching of helper

docs/.vscode/settings.json, docs/eslint.config.js, docs/package.json, docs/pnpm-lock.yaml
- use switch in eslint preset
- update packages
- remove experimental setting
=> Docs - Fix astro formatting (hopefully) 

addons/backblast/Scripts/Game/ACE_Backblast/ACE_BackblastComponent.c
- Use new method for adding bleedings
=> Backblast - Fixes for experimental

addons/trenches/scripts/Game/ACE_Trenches/Building/SCR_CampaignBuildingGadgetToolComponent.c
- Update signature of `ToggleActive`
=> Trenches - Fixes for experimental

addons/medical/Prefabs/Items/Medicine/EpinephrineInjection/ACE_Medical_EpinephrineInjection.et
- Make preview orientation of epinephrine injector consistent with morphine injector.
- Remove old attributes from prefab
=> Medical - Fix preview orientation of epinephrine injector

addons/trenches/Prefabs/Items/Equipment/Accessories/ETool_ALICE/ETool_ALICE_FreeRoamBuilding_Gadget.et, addons/trenches/Prefabs/Items/Equipment/Accessories/ETool_ALICE/ETool_ALICE_FreeRoamBuilding_Gadget.et.meta, addons/trenches/Prefabs/Items/Equipment/Accessories/ETool_MPL50/ETool_MPL50_FreeRoamBuilding_Gadget.et, addons/trenches/Prefabs/Items/Equipment/Accessories/ETool_MPL50/ETool_MPL50_FreeRoamBuilding_Gadget.et.meta, addons/trenches/scripts/Game/ACE_Trenches/Building/SCR_CampaignBuildingGadgetToolComponent.c
- Fix script error caused by removal of `CanBeToggled`
=> Trenches - Fix for `1.2.0.66`

addons/medical/Prefabs/Items/Medicine/MorphineInjection_01/MorphineInjection_01.et
- Remove old entries from morphine prefab
=> Medical - Update morphine prefab

addons/magrepack/license.txt, docs/src/content/docs/components/magrepack.mdx
- Capitalize name in wiki, tweak formatting
- Add license
=> Magrepack - Fix documentation

addons/carrying/Scripts/Game/ACE_Carrying/Entities/ACE_Carrying_HelperCompartment.c
- Use the Dragger mod's approach for limiting the walking speed
- Move prone check to frame event
=> Carrying - Limit walking speed

addons/medical/Prefabs/Characters/Core/DamageManager_Character_Base.ct
- Change parent hit zone of from neck to pain.
- Resolves #102
=> Medical - Fix: Injuring left calf caused neck injuries

addons/carrying/Scripts/Game/ACE_Carrying/UserActions/ACE_Carrying_CarryUserAction.c
=> Carrying - Do not show carry action on unconscious players in vehicles

addons/medical/scripts/Game/ACE_Medical/Components/SupportStation/SCR_HealSupportStationComponent.c
=> Medical - Broadcast max heal setting to all clients

addons/carrying/Scripts/Game/ACE_Carrying/Entities/ACE_Carrying_HelperCompartment.c
- Limit walking speed by input magnitude
- Disable jumping input
- Use input manager for preventing prone stance
=> Carrying - Improve limiting movement of carrier

addons/finger/Configs/ACE/Settings.conf, addons/finger/Configs/ACE/Settings.conf.meta, addons/finger/scripts/Game/ACE_Finger/Editor/Components/Editor/ACE_Finger_EditorComponent.c, addons/finger/scripts/Game/ACE_Finger/Mission/ACE_MissionHeaderSettings.c, addons/finger/scripts/Game/ACE_Finger/Settings/ACE_Finger_Settings.c, docs/src/content/docs/components/finger.mdx
- Resolve https://github.com/acemod/ACE-Anvil/discussions/2#discussioncomment-8976502
- Add settings for pointing distance and share range.
=> Finger - Add settings for pointing

addons/finger/scripts/Game/ACE_Finger/Editor/UI/InfoDisplays/SCR_EditorPingInfoDisplay.c
- Exclude controlled entity rather than main entity from tracing
- Fix the issue that trying to ping inside a vehicle ended up pinging the vehicle
=> Finger - Fix pings from getting attached to yourself

addons/trenches/Configs/Systems/ChimeraSystemsConfig.conf, addons/trenches/Configs/Systems/ChimeraSystemsConfig.conf.meta, addons/trenches/PrefabsEditable/Auto/Compositions/Misc/FreeRoamBuilding/E_ACE_DirtCover_01_long_v1.et, addons/trenches/PrefabsEditable/Auto/Compositions/Misc/FreeRoamBuilding/E_ACE_DirtCover_01_short.et, addons/trenches/scripts/Game/ACE_Trenches/Components/ACE_Trenches_OutlineGarbageComponent.c
- Delete unbuilt trenches after 5 minutes (by default) if no player is next to it.
=> Trenches - Add garbage collection for unbuilt trenches

addons/chopping/Prefabs/Helpers/ACE_Chopping_BaseHelper.et
- Use the new floating action context feature that was added to building
=> Chopping - Add floating action context

addons/trenches/Common/Materials/ACE_Trenches_MatTerrainObj.emat, addons/trenches/Common/Materials/ACE_Trenches_MatTerrainObj.emat.meta, addons/trenches/Prefabs/Compositions/Misc/FreeRoamBuilding/ACE_DirtCover_01_long_v1.et, addons/trenches/Prefabs/Compositions/Misc/FreeRoamBuilding/ACE_DirtCover_01_short.et, addons/trenches/PrefabsEditable/Auto/Structures/Military/Fortifications/E_ACE_DirtCover_01_long_v1.et, addons/trenches/PrefabsEditable/Auto/Structures/Military/Fortifications/E_ACE_DirtCover_01_short.et, addons/trenches/PrefabsEditable/Auto/Structures/Military/Fortifications/E_ACE_DirtCover_Base.et
- Make the dirt covers adopt the material of the underlying terrain surface
=> Trenches - Use terrain material for dirt covers

docs/src/content/docs/components/finger.mdx, docs/src/content/docs/components/medical.mdx
=> Docs - Fix newline syntax

addons/explosives/Prefabs/Weapons/Core/Mine_base.et
- Make mines destructible again
=> Explosives - Fix mines are not destructible

addons/carrying/Prefabs/Helpers/ACE_Carrying_HelperCompartment.et
=> Carrying - Fix carried player is attached to root instead of shoulder on clients

addons/explosives/Prefabs/Weapons/Core/Mine_base.et
=> Explosives - Make mines immune to bullets and melee

addons/core/Configs/Commanding/Commands.conf, addons/core/Configs/Commanding/Commands.conf.meta, addons/core/Configs/Commanding/EmoteMenu.conf, addons/core/Configs/Commanding/EmoteMenu.conf.meta, addons/core/Language/ACE_localization.cs_cz.conf, addons/core/Language/ACE_localization.de_de.conf, addons/core/Language/ACE_localization.en_us.conf, addons/core/Language/ACE_localization.es_es.conf, addons/core/Language/ACE_localization.fr_fr.conf, addons/core/Language/ACE_localization.it_it.conf, addons/core/Language/ACE_localization.ja_jp.conf, addons/core/Language/ACE_localization.ko_kr.conf, addons/core/Language/ACE_localization.pl_pl.conf, addons/core/Language/ACE_localization.pt_br.conf, addons/core/Language/ACE_localization.ru_ru.conf, addons/core/Language/ACE_localization.st, addons/core/Language/ACE_localization.uk_ua.conf, addons/core/Language/ACE_localization.zh_cn.conf
- Make sit and pushup available in radial menu for gestures
- Add display names to radial menu for gestures
=> Core - Make sit and pushups gestures available

addons/medical/Language/ACE_Medical_localization.cs_cz.conf, addons/medical/Language/ACE_Medical_localization.de_de.conf, addons/medical/Language/ACE_Medical_localization.en_us.conf, addons/medical/Language/ACE_Medical_localization.es_es.conf, addons/medical/Language/ACE_Medical_localization.fr_fr.conf, addons/medical/Language/ACE_Medical_localization.it_it.conf, addons/medical/Language/ACE_Medical_localization.ja_jp.conf, addons/medical/Language/ACE_Medical_localization.ko_kr.conf, addons/medical/Language/ACE_Medical_localization.pl_pl.conf, addons/medical/Language/ACE_Medical_localization.pt_br.conf, addons/medical/Language/ACE_Medical_localization.ru_ru.conf, addons/medical/Language/ACE_Medical_localization.st, addons/medical/Language/ACE_Medical_localization.uk_ua.conf, addons/medical/Language/ACE_Medical_localization.zh_cn.conf, addons/medical/Prefabs/Characters/Core/Character_Base.et, addons/medical/anims/workspaces/player/Unconscious.agf, addons/medical/anims/workspaces/player/Unconscious.agf.meta, addons/medical/scripts/Game/ACE_Medical/Character/ACE_Medical_EUnconsciousPose.c, addons/medical/scripts/Game/ACE_Medical/Character/SCR_CharacterControllerComponent.c, addons/medical/scripts/Game/UserActions/ACE_Medical_RepositionUserAction.c
- Modifies unconscious animation graph to allow transitions between different poses
- Add user actions to reposition unconscious players to back or recovery positions
=> Medical - Add repositioning actions

addons/core/scripts/Game/ACE_Core/Components/ACE_CarriableEntityComponent.c, addons/core/scripts/Game/ACE_Core/UserActions/ACE_BaseGadgetUserAction.c
=> Captives - Handle null exceptions

addons/core/scripts/Game/ACE_Core/Components/ACE_CarriableEntityComponent.c, addons/core/scripts/Game/ACE_Core/Player/SCR_PlayerController.c, addons/core/scripts/Game/ACE_Core/UserActions/ACE_BaseGadgetUserAction.c
- Remove duplicate code in `SCR_PlayerController.c` from improper merge
=> Core - Remove duplicate code

addons/tactical_ladder/Language/ACE_TacticalLadder_localization.cs_cz.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.de_de.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.en_us.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.es_es.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.fr_fr.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.it_it.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.ja_jp.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.ko_kr.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.pl_pl.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.pt_br.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.ru_ru.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.st, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.uk_ua.conf, addons/tactical_ladder/Language/ACE_TacticalLadder_localization.zh_cn.conf, addons/tactical_ladder/scripts/Game/ACE_TacticalLadder/Entities/ACE_TacticalLadderEntity.c, addons/tactical_ladder/scripts/Game/ACE_TacticalLadder/UserActions/ACE_TacticalLadder_LadderUserAction.c
- Add obstruction check for top exit
- Add cannot perform reason for too short ladder and obstructed top exit
=> Tactical Ladder - Add obstruction check for top exit

addons/tactical_periscope/Prefabs/Items/Equipment/Periscope/ACE_TacticalPeriscope.et, addons/tactical_periscope/scripts/Game/ACE_TacticalPeriscope/Components/Gadgets/ACE_TacticalPeriscope_GadgetComponent.c
=> Tactical Periscope - Fix periscope was visible when gear has a binocular slot.

addons/tactical_ladder/Prefabs/Items/Equipment/TacticalLadder/ACE_TacticalLadder.et
=> Tactical Ladder - Fix display name when replacing ladder

addons/tactical_ladder/scripts/Game/ACE_TacticalLadder/Entities/ACE_TacticalLadderEntity.c
- Ensure that ladders are placed on the ground and upright when dropped from inventory.
=> Tactical Ladder - Fix placement when dropped from inventory

addons/captives/scripts/Game/ACE_Captives/Systems/ACE_Captives_CaptiveSystem.c
- Remove last instigator when becoming captive.
=> Captives - Fix last instigator getting punished when captive respawns

docs/_redirects, docs/package.json, docs/pnpm-lock.yaml
=> Docs - Add Netlify redirects for subpaths

docs/_redirects, docs/public/_redirects
=> Docs - Fix _redirects file not in dist/ output

AUTHORS, addons/medical_prototypes/Language/ACE_MedicalPrototypes_localization.st
- Add Ukrainian translations by ArtOfWar
=> Medical prototypes - Add UA translations
